config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  root to: 'homes#top'
  
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  get '/home/about', to: 'homes#about', as: 'about'
  
  get '/search' => 'search#search'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :book_comments, dependent: :destroy
    has_many :favorites,dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end


validates :title, presence: true
validates :body, length: { maximum: 200 },presence: true
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  # has_many :favorites,dependent: :destroy
  # コメントアウト理由はfavoriteのmodel参照

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  # belongs_to :book_comment
  # コメント機能にもいいね付けたくアソシエーションしたが、いいねする際に「コメントが空白のためエラー」が発生し、いいねがsaveされなかったためコメントアウト
  # 上のエラーちょっと意味が違うかも、favoritesテーブルのbook_comment_idがブランクになってしまうから保存できないという意味か？
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites,dependent: :destroy
  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
    has_many :followers, through: :reverse_of_relationships, source: :follower
    # 被フォロー関係を通じて参照→followed_idをフォローしている人

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
    # 【class_name: "Relationship"】は省略可能
    has_many :followings, through: :relationships, source: :followed
    # 与フォロー関係を通じて参照→follower_idをフォローしている人
    
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
  
  attachment :profile_image

  validates :name, uniqueness: true,length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :authenticate_user!,except: [:top,:about]

def after_sign_in_path_for(resource)
   user_path(current_user.id)
end


before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end


end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @books = Book.find(params[:book_id])
    
    @book_comment = BookComment.new(book_comment_params)
    @book_comment.user_id = current_user.id
    
    @book_comment.book_id = @books.id
    @book_comment.save
    render :index

  end

  def destroy
    @books = Book.find(params[:book_id])
    @book_comment = BookComment.new
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    render :index
  end

private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
     @book = Book.new
     @user = current_user
     @books = Book.all

     #@users = Book.find(user_id)
  end

  def create
   @user = current_user
   @books =Book.all
   @book = Book.new(book_params)
   @book.user_id = current_user.id
   if @book.save
      flash[:notice] = "You have created book successfully."
       redirect_to book_path(@book)
   else
      render 'index'
   end
  end

  def show
    @book = Book.new
    @books = Book.find(params[:id])
    @user = @books.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
     unless
    @book.user == current_user
     redirect_to books_path
     end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(params[:id])
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

 private
  def book_params
    params.require(:book).permit(:title,:body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.new(book_id: @book.id)
    @favorite.save!
    render:index
  end

  def destroy
 
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @book.id)
    @favorite.destroy
    render:index

  end
  
  private
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end 
  
  def about
  end
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    
# ——————フォロー機能を作成・保存・削除する————————————
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer  
  end
#————————フォロー・フォロワー一覧を表示する- ————————————
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
  
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @content = params["content"]
    @model = params["model"]
    @method = params["method"]
    @records = search_for(@model, @content, @method)
  end

  private
  def search_for(model, content, method)
    if model == 'user'
      if method == 'perfect'
        User.where(name: content)
      elsif method == 'partial'
        User.where('name LIKE ?', '%'+content+'%')
      elsif method == 'forward'
        User.where('name LIKE ?', content+'%')
      elsif method == 'backward'
        User.where('name LIKE ?', '%'+content)
      end
      
    elsif model == 'book'
      if method == 'perfect'
        Book.where(title: content)
      elsif method == 'partial'
        Book.where('title LIKE ?', '%'+content+'%')
      elsif method == 'forward'
        Book.where('title LIKE ?', content+'%')
      elsif method == 'backward'
        Book.where('title LIKE ?', '%'+content)
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
     @book = Book.new
     @user = current_user
     @users = User.all
     #@users = Book.find(user_id)
  end
  
  def show
    @book = Book.new
    @user = User.find(params[:id])
    @userbook = @user.books.page(params[:page]).reverse_order
  end
  
  def create
  end
  
  def edit
    @user = User.find(params[:id])
    unless 
    @user. == current_user
     redirect_to user_path(current_user.id)
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id) 
    else
      render 'edit'
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :profile_image,:introduction)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/index.js.erb
$(".comment_area").html("<%= j(render 'books/BookComment', { books: @books,book_comment: @book_comment }) %>")
$("textarea").val('')

app/views/books/_BookComment.html.erb
    <div class="comments">
     <table>
       <thead>
         <tr>
         </tr>
       </thead>
       <tbody>
            <% books.book_comments.each do |book_comment| %>
            <tr>
              <td>
                <%= link_to user_path(book_comment.user) do %>
                <%= attachment_image_tag book_comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %><br>
                <%= book_comment.user.name %>
                <% end %>
              </td>

              <!--<td><%#= book_comment.created_at.strftime('%Y/%m/%d') %></td>-->
              <td><%= book_comment.comment %></td>

              <% if book_comment.user == current_user %>
              <td>
                <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment),class:'btn btn-sm btn-danger destroy_book_765',method: :delete,remote: true %>
              </td>
              <% end %>

            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
    

app/views/books/_BookFavorite.html.erb
        <% if book.favorited_by?(current_user) %>
          <p class="iine_yame"><%= link_to book_favorites_path(book.id), method: :delete,remote: true do %>
              ♥<%= book.favorites.count %> いいね
            <% end %>
          </p>
          <% else %>
          <p class="iine_suru"><%= link_to book_favorites_path(book.id), method: :post,remote: true do %>
              ♡<%= book.favorites.count %> いいね
            <% end %>
          </p>
        <% end %>

app/views/books/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        
        <% if @book.errors.any? %>
        <div class="error_explanation">
          <h2><%= @book.errors.count %> error prohibited this obj from being saved:</h2>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
        </div>
        <% end %>
                
            <%= form_with model:@book, local:true do |f| %>
            <div class="form-group">
              <label for="inputName">Title</label>
              <%= f.text_field :title, autofocus: true, id:"inputName", placeholder:"名前"%>
            </div>
            <div class="form-group">
              <label for="introduction">Opinion</label>
              <%= f.text_field :body, autofocus: true, id:"introduction", placeholder:"自己紹介文"%>
            </div>
              <%= f.submit "Update Book" ,class:'btn btn-success'%>
            <% end %>

              <%=(link_to"Show", book_path(params[:id]) ,{class: "book"})%>
            |
              <%=(link_to"Back", books_path, {class: "book"})%>
    </div>
   </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
<div class="container px-5 px-sm-0">

  <% if @book.errors.any? %>
  <div class="error_explanation">
    <h2><%= @book.errors.count %> error prohibited this obj from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
  </div>
  <% end %>

  <div class="row">
   <div class="col-md-3">
     <%= render partial: 'users/sidebar', locals: { user: @user, book: @book } %>
   </div>


   <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
    <thead>
        <tr>
          <th colspan="0"></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="2"></th>
        </tr>
    </thead>
    <tbody>
    <% @books.each do |book| %>
        <tr>
          <td>
          <!--ここを治す@userのところ_ |book| ←このローカル変数に.userでOK（indexにURLはないが、@booksで中身を全部持ってきている＝user_idも持ってきているのでレコード毎に区切っているbookに.userをつけた-->
          <%= link_to user_path(book.user) do %>
           <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
          <% end %>
          </td>
          <td>
            <%= link_to book_path(book.id) do %>
            <%= book.title %>
            <% end %>
            </td>
          <td><%= book.body %></td>
          
        <td class="favorite_area">    
        <%= render partial: 'BookFavorite', locals:{book: book}  %>
        </td>

        <td>コメント数： <%= book.book_comments.count %></td>

        <% end %>
       </tr>

    </tbody>
    </table>
    </div>
  </div>
</div>
</main>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
   <div class="col-md-3">
     <%= render partial: 'users/sidebar', locals: { user: @user, book: @book } %>
   </div>
  <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
    <table class="table">
    <tbody class ="BookShow">
        <tr>
          <td>
            <%= link_to user_path(@user) do %>
            <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %><br>
            <%= @user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(params[:id]) do %>
            <%= @books.title %>
            <% end %>
            </td>
          <td>
            <%= @books.body %>
          </td>

          <td class="favorite_area">          
            <%= render partial: 'BookFavorite', locals:{book: @books}  %>
          </td>

          
          <td>
            コメント件数：<%= @books.book_comments.count %>
          </td>
          
          <td>
            <% if @books.user == current_user %>
            <div class=row>
              <%= link_to "Edit", edit_book_path(params[:id]),class:'btn btn-sm btn-success edit_book_765' %>
            </div>
            <% end %>
          </td>

          <td>
            <% if @books.user == current_user %>
              <div class=row>
                <%= link_to "Destroy", book_path(params[:id]),class:'btn btn-sm btn-danger destroy_book_765', method: :delete ,data: { confirm: '本当に消しますか？' } %>
              </div>
            <% end %>
          </td>
          
        </tr>
    </tbody>
    </table>
    
    <div class="comment_area">
     <%= render partial: 'BookComment', locals:{books: @books,book_comment: @book_comment}  %>
    </div>
    
    <div class="new-comment">
      <%= form_with(model:[@books, @book_comment], remote: true) do |f| %>
      <p><%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %></p>
      <p><%= f.submit "送信する" %></p>
      <% end %>
    </div>
    
</div>
</div>
</div>

app/views/favorites/index.js.erb
$(".favorite_area").html("<%= j(render 'books/BookFavorite', { book: @book, }) %>")

app/views/homes/about.html.erb
<main>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">
        Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>
      </h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <div class="container">
    <div class="row">

      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>
          welcome to
          <i class="fas fa-book"></i><strong>Bookers</strong>
          !!
        </h1>
        <p>In <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p>about various books!</p>

        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to("Log in", new_user_session_path,{class: "btn btn-info btn-sm btn-block mb-3 sign_in"}) %>
          </div>
          <div class="row">
            <%= link_to("Sign Up", new_user_registration_path,{class: "btn btn-success btn-sm btn-block sign_up"}) %>
          </div>
      </div>
    </div>
   </div>
  </div>
</main>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
<table class="table table-hover table-inverse">
    <thead>
        <tr>
          <th>image</th>
          <th>Name</th>
          <th colspan="9"></th>
        </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
        <tr>
          <td>
          <!--ここを治す@userのところ_ |book| ←このローカル変数に.userでOK（indexにURLはないが、@booksで中身を全部持ってきている＝user_idも持ってきているのでレコード毎に区切っているbookに.userをつけた-->
          <%= link_to user_path(user.id) do %>
           <%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
          <% end %>
          </td>
          <td>
            <%= user.name %>
          </td>
          
          <td>フォロー数：<%= user.followings.count %></td>
          <td>フォローワー数：<%= user.followers.count %></td>
          <td>
        　<% unless current_user == user %>
              <% if current_user.following?(user) %>
                <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
                
              <% else %>
                <%= link_to "フォローする", user_relationships_path(user.id) , method: :post %>
              <% end %>
        　<% end %>
        　</td>

          <td>
            <%= link_to "Show", user_path(user.id)  %>
          </td>
        </tr>

    <% end %>
    </tbody>
    </table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
<table class="table table-hover table-inverse">
    <thead>
        <tr>
          <th>image</th>
          <th>Name</th>
          <th colspan="9"></th>
        </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
        <tr>
          <td>
          <!--ここを治す@userのところ_ |book| ←このローカル変数に.userでOK（indexにURLはないが、@booksで中身を全部持ってきている＝user_idも持ってきているのでレコード毎に区切っているbookに.userをつけた-->
          <%= link_to user_path(user.id) do %>
           <%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
          <% end %>
          </td>
          <td>
            <%= user.name %>
          </td>
          
          <td>フォロー数：<%= user.followings.count %></td>
          <td>フォローワー数：<%= user.followers.count %></td>
          <td>
        　<% unless current_user == user %>
              <% if current_user.following?(user) %>
                <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
                
              <% else %>
                <%= link_to "フォローする", user_relationships_path(user.id) , method: :post %>
              <% end %>
        　<% end %>
        　</td>

          <td>
            <%= link_to "Show", user_path(user.id)  %>
          </td>
        </tr>

    <% end %>
    </tbody>
    </table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/search/search.html.erb
<% if @model == 'user' %>
  <h3>【Usersモデルの検索結果】検索ワード</h3>
  <table class="table table-hover table-inverse">
    <thead>
        <tr>
          <th>image</th>
          <th>Name</th>
          <th colspan="9"></th>
        </tr>
    </thead>
    <tbody>
    <% @records.each do |user| %>
        <tr>
          <td>
          <!--ここを治す@userのところ_ |book| ←このローカル変数に.userでOK（indexにURLはないが、@booksで中身を全部持ってきている＝user_idも持ってきているのでレコード毎に区切っているbookに.userをつけた-->
          <%= link_to user_path(user.id) do %>
           <%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
          <% end %>
          </td>
          <td>
            <%= user.name %>
          </td>
          
          <td>フォロー数：<%= user.followings.count %></td>
          <td>フォローワー数：<%= user.followers.count %></td>
          <td>
        　<% unless current_user == user %>
              <% if current_user.following?(user) %>
                <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
                
              <% else %>
                <%= link_to "フォローする", user_relationships_path(user.id) , method: :post %>
              <% end %>
        　<% end %>
        　</td>

          <td>
            <%= link_to "Show", user_path(user.id)  %>
          </td>
        </tr>

    <% end %>
    </tbody>
    </table>
<% end %>

<% if @model == 'book' %>
  <h3>【Bookモデルの検索結果】検索ワード</h3>
  
  <table class="table table-hover table-inverse">
    <thead>
        <tr>
          <th colspan="0"></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="0"></th>
        </tr>
    </thead>
    <tbody>
    <% @records.each do |book| %>
        <tr>
          <td>
          <!--ここを治す@userのところ_ |book| ←このローカル変数に.userでOK（indexにURLはないが、@booksで中身を全部持ってきている＝user_idも持ってきているのでレコード毎に区切っているbookに.userをつけた-->
          <%= link_to user_path(book.user) do %>
           <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
          <% end %>
          </td>
          <td>
            <%= link_to book_path(book.id) do %>
            <%= book.title %>
            <% end %>
            </td>
          <td><%= book.body %></td>

        <td>
         <% if book.favorited_by?(current_user) %>
          <p><%= link_to book_favorites_path(book.id), method: :delete do %>
              ♥<%= book.favorites.count %> いいね
            <% end %>
          </p>

          <% else %>
          <p><%= link_to book_favorites_path(book.id), method: :post do %>
              ♡<%= book.favorites.count %> いいね
            <% end %>
          </p>
        <% end %>
        </td>

        <td>コメント数： <%= book.book_comments.count %></td>

        <% end %>
       </tr>

    </tbody>
    </table>
<% end %>

app/views/users/_sidebar.html.erb
<!--ログイン後のほぼ共通パーツ ここから-->
 <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr>
        
      </tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th colspan=0><%= user.introduction %></th>
      </tr>

      <tr>
        <th>follows</th>
        <th colspan=0><%= link_to user.followings.count, user_followings_path(user)%></th>
      </tr>
      
      <tr>
        <th>followers</th>
        <th colspan=0><%= link_to user.followers.count, user_followers_path(user)%></th>
      </tr>
      
  </tbody>
  </table>
<div class=row>
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= link_to "フォロー外す", user_relationships_path(user.id), class: 'btn btn-danger btn-block' , method: :delete %>
    
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), class: 'btn btn-primary btn-block' , method: :post %>
  <% end %>
<% end %>
</div>

<p></p><!--margin代わりpタグ-->

<div class=row><%= link_to("", edit_user_path(user),{class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_266"}) %></div>
  
  
<h2 class="mt-3">New book</h2>
<%= form_with model: book, local:true do |f| %>
  <div class="form-group">
    <label>Title </label>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <label>Opinion </label>
    <%= f.text_area :body %>
  </div>
  <div class="form-group">
  <%= f.submit 'Create Book' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        
      
        <% if @user.errors.any? %>
         <div class="error_explanation">
          <h2><%= @user.errors.count %> error prohibited this obj from being saved:</h2>
           <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
         </div>
        <% end %>
      
        
        <%= form_with model:@user, local:true do |f| %>
          <div class="form-group">
            <label for="inputName">Name</label>
            <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
          </div>
          
          <div class="form-group">
            <label for="inputImage">Image</label>
            <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
          </div>
          
          <div class="form-group">
            <label for="introduction">introduction</label>
            <%= f.text_field :introduction, autofocus: true, id:"introduction", placeholder:"自己紹介文"%>
          </div>
          
          <div class="form-group">
            <%= f.submit "Update User" ,:class => 'btn btn-secondary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
   <div class="col-md-3">
     <%= render partial: 'users/sidebar', locals: { user: @user, book: @book } %>
   </div>


   <div class="col-md-8 offset-md-1">
    <h2>Users</h2>
    <table class="table table-hover table-inverse">
    <thead>
        <tr>
          <th>image</th>
          <th>Name</th>
          <th colspan="9"></th>
        </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
        <tr>
          <td>
          <!--ここを治す@userのところ_ |book| ←このローカル変数に.userでOK（indexにURLはないが、@booksで中身を全部持ってきている＝user_idも持ってきているのでレコード毎に区切っているbookに.userをつけた-->
          <%= link_to user_path(user.id) do %>
           <%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
          <% end %>
          </td>
          <td>
            <%= user.name %>
          </td>
          
          <td>フォロー数：<%= user.followings.count %></td>
          <td>フォローワー数：<%= user.followers.count %></td>
          <td>
        　<% unless current_user == user %>
              <% if current_user.following?(user) %>
                <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
                
              <% else %>
                <%= link_to "フォローする", user_relationships_path(user.id) , method: :post %>
              <% end %>
        　<% end %>
        　</td>

          <td>
            <%= link_to "Show", user_path(user.id)  %>
          </td>
        </tr>

    <% end %>
    </tbody>
    </table>
    </dev>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
   <div class="col-md-3">
     <%= render partial: 'users/sidebar', locals: { user: @user, book: @book } %>
   </div>
   <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
    <thead>
        <tr>
          <th colspan="0"></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="0"></th>
        </tr>
    </thead>
     <tbody>
    <% @userbook.each do |book| %>
        <tr>
          <td>
          <%= link_to user_path(@user) do %>
           <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
          <% end %>
          </td>
          <td>
            <%= link_to book_path(book.id) do %>
            <%= book.title %>
            <% end %>
            </td>
          <td><%= book.body %></td>
          <td>コメント件数：<%= book.book_comments.count %></td>
        </tr>
    <% end %>
    </table>
     </tbody>
    </div>
   </div>
  </div>