config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  root to: 'homes#top'
  
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  get '/home/about', to: 'homes#about', as: 'about'
  
  get '/search' => 'search#search'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :book_comments, dependent: :destroy
    has_many :favorites,dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end


validates :title, presence: true
validates :body, length: { maximum: 200 },presence: true
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  # has_many :favorites,dependent: :destroy
  # コメントアウト理由はfavoriteのmodel参照

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  # belongs_to :book_comment
  # コメント機能にもいいね付けたくアソシエーションしたが、いいねする際に「コメントが空白のためエラー」が発生し、いいねがsaveされなかったためコメントアウト
  # 上のエラーちょっと意味が違うかも、favoritesテーブルのbook_comment_idがブランクになってしまうから保存できないという意味か？
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites,dependent: :destroy
  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
    has_many :followers, through: :reverse_of_relationships, source: :follower
    # 被フォロー関係を通じて参照→followed_idをフォローしている人

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
    # 【class_name: "Relationship"】は省略可能
    has_many :followings, through: :relationships, source: :followed
    # 与フォロー関係を通じて参照→follower_idをフォローしている人
    
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
  
  attachment :profile_image

  validates :name, uniqueness: true,length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :authenticate_user!,except: [:top,:about]

def after_sign_in_path_for(resource)
   user_path(current_user.id)
end


before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
     @book = Book.new
     @user = current_user
     @books = Book.all

     #@users = Book.find(user_id)
  end

  def create
   @user = current_user
   @books =Book.all
   @book = Book.new(book_params)
   @book.user_id = current_user.id
   if @book.save
      flash[:notice] = "You have created book successfully."
       redirect_to book_path(@book)
   else
      render 'index'
   end
  end

  def show
    @book = Book.new
    @books = Book.find(params[:id])
    @user = @books.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
     unless
    @book.user == current_user
     redirect_to books_path
     end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(params[:id])
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

 private
  def book_params
    params.require(:book).permit(:title,:body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.new(book_id: @book.id)
    @favorite.save!
    render:index
  end

  def destroy
 
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @book.id)
    @favorite.destroy
    render:index

  end
  
  private
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end 
  
  def about
  end
  
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @content = params["content"]
    @model = params["model"]
    @method = params["method"]
    @records = search_for(@model, @content, @method)
  end

  private
  def search_for(model, content, method)
    if model == 'user'
      if method == 'perfect'
        User.where(name: content)
      elsif method == 'partial'
        User.where('name LIKE ?', '%'+content+'%')
      elsif method == 'forward'
        User.where('name LIKE ?', content+'%')
      elsif method == 'backward'
        User.where('name LIKE ?', '%'+content)
      end
      
    elsif model == 'book'
      if method == 'perfect'
        Book.where(title: content)
      elsif method == 'partial'
        Book.where('title LIKE ?', '%'+content+'%')
      elsif method == 'forward'
        Book.where('title LIKE ?', content+'%')
      elsif method == 'backward'
        Book.where('title LIKE ?', '%'+content)
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
     @book = Book.new
     @user = current_user
     @users = User.all
     #@users = Book.find(user_id)
  end
  
  def show
    @book = Book.new
    @user = User.find(params[:id])
    @userbook = @user.books.page(params[:page]).reverse_order
  end
  
  def create
  end
  
  def edit
    @user = User.find(params[:id])
    unless 
    @user. == current_user
     redirect_to user_path(current_user.id)
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id) 
    else
      render 'edit'
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :profile_image,:introduction)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
       <div class="container">

       <a href="/">
         <span class="navbar-brand">Bookers</span>
       </a>

       <!--要件にaタグで書くよう指示があったためコメントアウトし上記aタグ作成-->
       <%# link_to("Bookers","/",  {class: "navbar-brand"}) %>
       <!--課題3合格済-->

       <div class="collapse navbar-collapse">
    <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
     <li>
        <%= link_to("Home", user_path(current_user.id),{class: "fas fa-home nav-link text-light"}) %>
      </li>
     <li>
        <%= link_to("Users", users_path, {class: "fas fa-users nav-link text-light"}) %>
      </li>
     <li>
        <%= link_to("Books", '/books',{class: "fas fa-book-open nav-link text-light"}) %>
      </li>
      <li>
        <%= link_to("logout", destroy_user_session_path, {method: :delete,class: "fas fa-sign-out-alt nav-link text-light"}) %>
      </li>
    <% else %>
      <li>
      <%= link_to("Home", "/",{class: "fas fa-home nav-link text-light"} )%>
      </li>
      <li>
        <%= link_to("About", about_path,{class: "fas fa-link nav-link text-light"} )%>
      </li>
      <li>
     <%= link_to("sign up", new_user_registration_path,{class: "fas fa-user-plus nav-link text-light"} )%>
      </li>
      <li>
        <%= link_to("login", new_user_session_path,{class: "fas fa-sign-in-alt nav-link text-light"} )%>
      </li>
    <% end %>
    </ul>
    </div>
    </div>
        </nav>
        
<% if user_signed_in? %>
　<div class="serchbar">
    <%= form_tag(search_path, method: :get) do %>
      <%= text_field_tag 'content' %>
      <%= select_tag 'model', options_for_select({ "User" => "user", "Book" => "book" }) %>
      <%= select_tag 'method', options_for_select({ "完全一致" => "perfect", "部分一致" => "partial","前方一致"=>"forward","後方一致"=>"backward" }) %>
      <%= submit_tag '検索' %>
  </div>
    <% end %>
<% end %>
    </header>

    <main>
    <% flash.each do |message_type, message|%>
    <%= content_tag :div, message, class: message_type %>
    <% end %>
    <p id="notice"></p>
      <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>